# Generated by Django 4.0.2 on 2022-02-24 06:34

from django.db import migrations, models
import uuid
import videomerge.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='convertedVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to=videomerge.models.file_rename)),
                ('audio', models.FileField(upload_to=videomerge.models.file_rename)),
                ('output_video', models.FileField(upload_to='video')),
            ],
        ),
    ]
