# Generated by Django 4.0.2 on 2022-02-24 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='textToSpeech',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text_file', models.FileField(upload_to='audio/temp')),
                ('speech', models.FileField(upload_to='audio')),
            ],
        ),
    ]
